# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Ensure Focalboard paths exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0750"
    owner: "{{ focalboard_uid }}"
    group: "{{ focalboard_gid }}"
  with_items:
    - "{{ focalboard_base_path }}"
    - "{{ focalboard_data_path }}"
    - "{{ focalboard_config_path }}"

- name: Ensure Focalboard support files created
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item }}.j2"
    dest: "{{ focalboard_base_path }}/{{ item }}"
    owner: "{{ focalboard_uid }}"
    group: "{{ focalboard_gid }}"
    mode: 0640
  with_items:
    - env
    - labels

- name: Ensure Focalboard configuration created
  ansible.builtin.copy:
    content: "{{ focalboard_configuration | to_nice_json }}"
    dest: "{{ focalboard_config_path }}/config.json"
    owner: "{{ focalboard_uid }}"
    group: "{{ focalboard_gid }}"
    mode: 0640

- name: Ensure Focalboard image is pulled
  community.docker.docker_image:
    name: "{{ focalboard_container_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ focalboard_container_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else focalboard_container_image_force_pull }}"

- name: Ensure Focalboard container network is created
  community.general.docker_network:
    enable_ipv6: "{{ devture_systemd_docker_base_ipv6_enabled }}"
    name: "{{ focalboard_container_network }}"
    driver: bridge
    driver_options: "{{ devture_systemd_docker_base_container_networks_driver_options }}"

- name: Ensure Focalboard systemd service installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/focalboard.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ focalboard_identifier }}.service"
    mode: 0640
